name: Build and Push Docker Images
on: push
jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - run: make build
    - run: make push
